Repository nextcloud/serverinfo, pull requests merged in 2020-09, with the labels that each got.

#224 Add disk object
  lib/OperatingSystems/DefaultOs.php
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/IOperatingSystem.php
  lib/Os.php
  lib/Resources/Disk.php
  templates/settings-admin.php
  tests/lib/DefaultOsTest.php
Labels: 3. to review, enhancement

#231 Normalize memory and disk values to MB
  lib/OperatingSystems/DefaultOs.php
  lib/OperatingSystems/FreeBSD.php
  lib/Resources/Disk.php
  lib/Resources/Memory.php
  templates/settings-admin.php
  tests/lib/DefaultOsTest.php
  tests/lib/FreeBSDTest.php
Labels: 3. to review, bug

#235 Update calculation for used and available disk space in gigabyte.
  lib/Os.php
Labels: 3. to review, bug

#238 Various design and typography improvements
  css/style.scss
  templates/settings-admin.php
Labels: 3. to review, backport-request, design, enhancement
