Repository nextcloud/serverinfo, pull requests merged in 2020-10, with the labels that each got.

#240 Fix Memory
  lib/OperatingSystems/FreeBSD.php
  tests/lib/FreeBSDTest.php
Labels: 2. developing, backport-request, bug

#244 Replace function with constants
  lib/PhpStatistics.php
Labels: 3. to review, enhancement

#243 Remove timeserver
  js/script.js
  lib/Controller/ApiController.php
  lib/OperatingSystems/DefaultOs.php
  lib/OperatingSystems/FreeBSD.php
  lib/Os.php
  templates/settings-admin.php
Labels: 3. to review, enhancement

#245 [20] Fix Memory (#240)
  lib/OperatingSystems/FreeBSD.php
  tests/lib/FreeBSDTest.php
Labels: 3. to review, bug
