Repository nextcloud/serverinfo, pull requests merged in 2020-06, with the labels that each got.

#213 Move to new bootstrap mechanism
  appinfo/app.php
Labels: 3. to review, enhancement

#214 Remove unused dependencies
  lib/Os.php
Labels: 3. to review, technical debt

#216 Add tests for FreeBSD meminfo
  lib/OperatingSystems/FreeBSD.php
  tests/data/freebsd_meminfo
  tests/data/freebsd_swapinfo
  tests/lib/FreeBSDTest.php
Labels: 3. to review, bug

#212 Add status information about the opcache and APCu instances
  lib/PhpStatistics.php
Labels: 3. to review, enhancement
