Repository nextcloud/serverinfo, pull requests merged in 2021-04, with the labels that each got.

#294 Hide free space if it can't be calculated
  lib/SystemStatistics.php
  templates/settings-admin.php
Labels: 3. to review, bug

#297 move counting storage statistics to the background
  README.md
  appinfo/info.xml
  lib/Commands/UpdateStorageStats.php
  lib/Jobs/UpdateStorageStats.php
  lib/StorageStatistics.php
Labels: 3. to review, backport-request, bug

#288 Use strict typing
  appinfo/routes.php
  lib/Commands/UpdateStorageStats.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/DatabaseStatistics.php
  lib/Jobs/UpdateStorageStats.php
  lib/OperatingSystems/DefaultOs.php
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/IOperatingSystem.php
  lib/Os.php
  lib/PhpStatistics.php
  lib/SessionStatistics.php
  lib/Settings/AdminSection.php
  lib/Settings/AdminSettings.php
  lib/ShareStatistics.php
  lib/StorageStatistics.php
  lib/SystemStatistics.php
  templates/settings-admin.php
  tests/bootstrap.php
  tests/lib/ApiControllerTest.php
  tests/lib/DefaultOsTest.php
  tests/lib/FreeBSDTest.php
  tests/lib/SessionStatisticsTest.php
Labels: 3. to review, enhancement

#289 Flip default in checkAuthorized
  lib/Controller/ApiController.php
Labels: 4. to release
