Repository nextcloud/serverinfo, pull requests merged in 2021-06, with the labels that each got.

#312 Add ratelimit to ServerInfo API endpoint
  lib/Controller/ApiController.php
Labels: 3. to review, backport-request

#300 Catch RuntimeException
  lib/OperatingSystems/FreeBSD.php
Labels: 3. to review, bug

#319 Fix Chart.js Syntax
  js/script.js
Labels: 3. to review
