Repository nextcloud/serverinfo, pull requests merged in 2022-01, with the labels that each got.

#350 add support for raspberry pi 4b
  lib/OperatingSystems/DefaultOs.php
Labels: 4. to release

#351 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#332 Update OCA\ServerInfo\OperatingSystems::getNetworkInterfaces()
  lib/OperatingSystems/DefaultOs.php
Labels: 4. to release

#355 Remove travis
  .travis.yml
Labels: 3. to review
