Repository nextcloud/serverinfo, pull requests merged in 2022-05, with the labels that each got.

#371 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#379 Prevent PHP errors when iterating network interfaces
  lib/OperatingSystems/DefaultOs.php
Labels: bug, 3. to review

#380 Create fixup.yml
  .github/workflows/fixup.yml
Labels: 3. to review, technical debt
