Repository nextcloud/serverinfo, pull requests merged in 2023-01, with the labels that each got.

#405 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#412 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#413 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#407 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#406 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#408 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#411 Feat/add net interface resource object
  lib/OperatingSystems/DefaultOs.php
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/IOperatingSystem.php
  lib/Os.php
  lib/Resources/NetInterface.php
  templates/settings-admin.php
  tests/data/freebsd_interface_lo0
  tests/data/freebsd_interfaces
  tests/data/freebsd_net_get_interfaces.json
  tests/data/linux_net_get_interfaces.json
  tests/lib/DefaultOsTest.php
  tests/lib/FreeBSDTest.php
  tests/lib/NetInterfaceTest.php
Labels: enhancement, 3. to review

#420 Replace "Active users" and "Shares" charts and replace custom tooltips on Disk chart.
  css/style.css
  js/script.js
  templates/settings-admin.php
Labels: 3. to review, backport-request
