Repository nextcloud/serverinfo, pull requests merged in 2023-08, with the labels that each got.

#488 feat: rename DefaultOs to Linux
  README.md
  lib/OperatingSystems/Dummy.php
  lib/OperatingSystems/Linux.php
  lib/Os.php
  tests/data/linux_df_tp
  tests/data/linux_meminfo
  tests/data/linux_uptime
  tests/lib/DummyTest.php
  tests/lib/LinuxTest.php
Labels: enhancement, 4. to release

#491 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#492 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#495 fix: remove hint about your disk is full notification
  templates/settings-admin.php
Labels: bug, 3. to review

#496 chore: add value object for thermal zone
  js/script.js
  lib/Controller/ApiController.php
  lib/OperatingSystems/IOperatingSystem.php
  lib/OperatingSystems/Linux.php
  lib/Resources/ThermalZone.php
  templates/settings-admin.php
Labels: enhancement, 3. to review

#500 chore: dont autoload ocp package
  composer.json
Labels: 3. to review
