Repository nextcloud/serverinfo, pull requests merged in 2023-05, with the labels that each got.

#443 With FreeBSD jails, networkinfo->gateway can be empty
  lib/OperatingSystems/FreeBSD.php
Labels: 3. to review

#446 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#445 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#442 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#449 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#450 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#451 Update settings-admin.php to add Exabyte
  templates/settings-admin.php
Labels: 3. to review

#456 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#457 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#452 Display the current opcache.revalidate_freq setting under PHP details
  lib/PhpStatistics.php
  templates/settings-admin.php
Labels: enhancement, 3. to review

#459 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#458 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
