Repository nextcloud/serverinfo, pull requests merged in 2023-11, with the labels that each got.

#501 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#519 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#518 fix: add flag to skip external requests
  README.md
  css/style.css
  js/script.js
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Settings/AdminSettings.php
  lib/SystemStatistics.php
  templates/settings-admin.php
Labels: bug, 3. to review

#520 [stable27] fix: add flag to skip external requests
  README.md
  css/style.css
  js/script.js
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Settings/AdminSettings.php
  lib/SystemStatistics.php
  templates/settings-admin.php
Labels: bug, 3. to review

#522 feat: make update data opt-in
  js/script.js
  lib/Controller/ApiController.php
  lib/SystemStatistics.php
  templates/settings-admin.php
Labels: enhancement, 3. to review

#523 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#525 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#524 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#526 feat: make apps updates opt-in by default
  js/script.js
  lib/Controller/ApiController.php
  templates/settings-admin.php
Labels: enhancement, 3. to review, pending documentation

#528 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#533 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#527 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
