Repository nextcloud/serverinfo, pull requests merged in 2024-08, with the labels that each got.

#655 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#657 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#656 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#658 fix: Display threads and not cores
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/Linux.php
  tests/lib/LinuxTest.php
Labels: bug, backport-request

#663 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#669 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated
