Repository nextcloud/serverinfo, pull requests merged in 2024-05, with the labels that each got.

#597 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#598 fix: handle disabled shell_exec
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/Linux.php
Labels: bug, 3. to review, backport-request

#602 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#605 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#603 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#604 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#606 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#608 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#609 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#607 chore: remove dns server
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/IOperatingSystem.php
  lib/OperatingSystems/Linux.php
  templates/settings-admin.php
Labels: 3. to review
