Repository nextcloud/serverinfo, pull requests merged in 2024-07, with the labels that each got.

#639 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#640 Migrate REUSE to TOML format
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#645 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#642 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#644 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#646 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#643 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#650 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#649 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#648 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#651 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#641 Use a more sensible format for load average
  js/script.js
Labels: bug, 3. to review, backport-request, feedback-requested
