Repository nextcloud/serverinfo, pull requests merged in 2024-06, with the labels that each got.

#611 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#612 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#613 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#615 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#619 ci: automate ocp updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: backport-request

#614 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#623 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#625 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#628 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#630 fix: handle getNetInterfaces error
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/Linux.php
  tests/lib/FreeBSDTest.php
  tests/lib/LinuxTest.php
Labels: bug, 3. to review, backport-request

#631 fix: update wording about apps element in monitoring response
  README.md
  templates/settings-admin.php
Labels: bug, 3. to review, backport-request

#624 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#637 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#638 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
