Repository nextcloud/serverinfo, pull requests merged in 2024-04, with the labels that each got.

#580 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#582 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#583 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#584 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#585 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#587 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#589 fix: replace removed success and complete callbacks
  js/script.js
Labels: bug, 3. to review, backport-request

#591 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#593 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#594 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#595 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
