Repository nextcloud/serverinfo, pull requests merged in 2024-10, with the labels that each got.

#694 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#674 Fix inaccurate disk usage reporting for ext* filesystems due to reserved blocks
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/Linux.php
  tests/lib/LinuxTest.php
Labels: bug, 3. to review, feedback-requested

#693 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#692 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#691 feat(active users): add more active user statistics intervals and improve presentation
  css/style.css
  lib/SessionStatistics.php
  templates/settings-admin.php
  tests/lib/SessionStatisticsTest.php
Labels: enhancement, design, 3. to review
