Repository nextcloud/serverinfo, pull requests merged in 2025-01, with the labels that each got.

#731 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#732 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/PhpInfoResponse.php
Labels: 3. to review, dependencies

#729 [stable30] Update nextcloud/ocp dependency
  composer.lock
  lib/PhpInfoResponse.php
Labels: 3. to review, dependencies

#730 [stable29] Update nextcloud/ocp dependency
  composer.lock
  lib/PhpInfoResponse.php
Labels: 3. to review, dependencies

#733 fix(freebsd): fix cpu count for load graph
  lib/OperatingSystems/FreeBSD.php
Labels: bug, 3. to review

#728 feat(storage): add size of appdata folder to statistics
  lib/Jobs/UpdateStorageStats.php
  lib/StorageStatistics.php
Labels: 3. to review

#735 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#739 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#740 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#741 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#742 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#738 Show php-fpm data if available
  lib/Controller/ApiController.php
  lib/FpmStatistics.php
  lib/Settings/AdminSettings.php
  templates/settings-admin.php
  tests/lib/ApiControllerTest.php
Labels: 2. developing
