Repository nextcloud/serverinfo, pull requests merged in 2025-03, with the labels that each got.

#756 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#757 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#758 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#759 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#761 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#760 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#762 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#764 [stable31] chore: update workflows
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, github_actions

#763 chore: update workflows
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, github_actions

#765 [stable30] chore: update workflows
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  psalm.xml
Labels: 3. to review, github_actions

#767 [stable29] chore: update workflows
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  psalm.xml
Labels: 3. to review, github_actions

#766 ci(actions): add yaml workflow
  .github/workflows/lint-yaml.yml
Labels: 3. to review, backport-request, github_actions

#771 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#772 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#775 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#776 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
