Repository nextcloud/serverinfo, pull requests merged in 2025-05, with the labels that each got.

#801 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#802 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#804 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#806 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#823 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#821 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#822 [stable31] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#785 chore: add override attribute
  lib/Commands/UpdateStorageStats.php
  lib/Jobs/UpdateStorageStats.php
  lib/OperatingSystems/Dummy.php
  lib/OperatingSystems/FreeBSD.php
  lib/OperatingSystems/Linux.php
  lib/Os.php
  lib/PhpInfoResponse.php
  lib/Resources/ThermalZone.php
  lib/Settings/AdminSection.php
  lib/Settings/AdminSettings.php
  psalm.xml
  tests/bootstrap.php
  tests/phpunit.xml
  tests/psalm-baseline.xml
Labels: 3. to review

#814 fix: get actual number of active users
  lib/SessionStatistics.php
  tests/lib/SessionStatisticsTest.php
Labels: bug, 3. to review, backport-request

#832 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#833 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
